image: php5.4
script:
  - mysql -u root -e "CREATE USER 'ubuntu'@'localhost'";
  - mysql -u root -e "CREATE USER 'localhost'@'localhost'";
  - composer up
  - phpunit test
services:
  - mysql:5.5
notify:
  email:
    recipients: